### ISSUE TITLE
Image from Arweave did not show up

### ISSUE THREAD

**Issue by fungibles** [bitclout/frontend#346] opened 2021-07-30 05:47 UTC
I uploaded this image to arweave, I embedded the image using this link in my post, when I saved my post the image didn't show up. I thought maybe if I mint the NFT it would show, but I did not show up. Not sure if this is user error with using the wrong link, or there is an issue with arweave

https://35bze7lo27jbbeipxtfsztcnrqniiplyyalctssn2vc7vbid62la.arweave.net/30OSfW7X0hCRD7zLLMxNjBqEPXjAFinKTdVF-oUD9pY

**Comment by tijno** [comment] 2021-07-30 15:04
Sometimes it can take a while for arweave assets to be available as its still being distributed through the network and waiting for confirmation. 

If you link the post/nft URL i can have a look to see if it loads now.

The URL above seems fine.

**Comment by tijno** [comment] 2021-07-30 15:09
I think its this one:
https://bitclout.com/nft/a5c64da489cd1f39e719fb3772b4180d5f7aa35ee1d747b755cbef2189a3845b

Looks like that does not include an image.

How did you add the arweave URL?

**Comment by fungibles** [comment] 2021-07-30 18:37
I simply pasted The preview URL that I shared in the original post. I’m on
my phone on Google or would put that again here but it looks like you have
access to it.

Thanks for looking into this

What’s odd is that the preview showed up when I pasted the image into the
arweave link on the post.

As soon as I saved it the image was nowhere to be found.

**Comment by fungibles** [comment] 2021-07-30 18:45
Also something to note this is a public folder on arweave so not sure why
this wouldn’t show.

**Comment by tijno** [comment] 2021-07-30 18:53
no image was stored with the post - this is why its not showing.

if if you entered a url when editing the post and it did show until you saved it - then maybe it did not store it for some weird reason.

**Comment by fungibles** [comment] 2021-07-30 20:55
Really appreciate you looking into this. What I still don't get is why the
image was not stored with the post. When I posted it in the ar preview
link, the imaged showed up, then when I saved post it disappeared. I really
wish that we could create the nft before posting about it so people dont
have to see me live testing. I am sure someone opened a ticket for this by
now. Anyways going to try it again.

**Comment by tijno** [comment] 2021-07-30 22:27
maybe try on a 2nd account ? 

see if you can follow exact steps from before and see if it happens again. 

dont mint it though - just the post part.

then reload to see if the image shows.

**Comment by fungibles** [comment] 2021-08-01 20:20
Is it possible I am trying to use too many characters? I am using clout plus and the post is over 800 characters. This might be the case I tested it on another account using "test"

**Comment by fungibles** [comment] 2021-08-01 20:43
Ok so I tested without using more than 280, it works on a test account but not on my fungibles account. I am at a loss here.

**Comment by dgsus** [comment] 2021-08-01 20:44
> Ok so I tested without using more than 280, it works on a test account but not on my fungibles account. I am at a loss here. 

if u want i can get on a zoom call  to check this with u. sent u a friend request on discord so we can connect.

**Comment by fungibles** [comment] 2021-08-01 20:51
Ok I found it, wow this was a wicked bug. So when you past the arweave image in a post, and you don't immediately click post, and lets say you click somewhere else on the site, somehow it is either stripping out or adding a character. Nasty little bug.

**Comment by tijno** [comment] 2021-08-02 16:01
@fungibles nice work getting to the bottom of it

are you sure the issue is not that when you click somewhere outside of the post you are drafting that it closes the post window?

thats what happened to me before

Can you let me know exactly what you did:

* start a post
* click the arweave button and paste URL in the input box
* wait (how long?)
* click outside the post (eg where)
* click submit

Were those the steps?

**Comment by fungibles** [comment] 2021-08-07 01:10
ya positive, if you just click anywhere outside of the post (I am not
closing the post window) this bug happens.

   - Go to home page - start writing a post
   - click the arweave button and paste arweave preview image URL in the
   input box
   - wait only seconds
   - clicked outside the post, on the right side of the feed by the daily
   gainers
   - click submit

**Comment by AdityaChaudhary0005** [comment] 2021-08-07 15:16
@fungibles did your post body has any URL ? It happened with me too when i add URL to post body

**Comment by maebeam** [comment] 2021-08-09 18:40
Are either of you using bitclout.plus? I experienced this issue with that extension

**Comment by iPaulPro** [comment] 2021-08-09 20:48
> Are either of you using bitclout.plus? I experienced this issue with that extension

Can confirm that plus hasn't been updated to account for the arweave field yet. Sounds like the culprit here.

**Comment by fungibles** [comment] 2021-08-12 05:44
yes and I am pretty sure this was the issue even though I wasn't able to
a/b test it. Thanks Maebeam

**Comment by fungibles** [comment] 2021-08-12 05:45
Ya I am thinking most likely this is the issue

**Comment by fungibles** [comment] 2021-08-12 05:45
no didn't have a URL

**Comment by maebeam** [comment] 2021-08-12 16:13
I'm pretty positive this is an issue with bitclout.plus. Closing for now.

**Closed by maebeam** 2021-08-12 16:13 UTC
