### ISSUE TITLE
False Diamond triggers

### ISSUE THREAD

**Issue by iPaulPro** [bitclout/frontend#394] opened 2021-08-16 13:07 UTC
There's an issue with the hover detection in the new Diamond slider.

<img src="https://user-images.githubusercontent.com/354227/129568188-57272d73-9de9-4341-8647-460b1bc670c4.gif" width="360">

Lots of reports of accidental diamond giving, and with the removal of the confirmation for $5 level this is bound to happen frequently.

attn @superzordon

**Comment by seanslater** [comment] 2021-08-16 13:50
I just mocked up this concept.... instead of horizontal,  it could go vertical.

You'd move up the list as you wanted to give more diamonds.  This would make it a more deliberate action and have the default as 1 diamond.

![vertical](https://user-images.githubusercontent.com/378385/129574323-e841a0d3-771f-499c-a660-72b7c34147d8.jpg)

**Comment by tijno** [comment] 2021-08-16 13:54
Added a gif to show the issue is also present on the other values but then is gone again in a small zone around the border of the box. 

![20210816-kv3js4Uw](https://user-images.githubusercontent.com/69529928/129574639-320865ec-c6c7-402d-ba95-61e77fc930df.gif)


I like @seanslater idea of vertical slider.

**Comment by tijno** [comment] 2021-08-16 14:07
This may be related to - when I click the diamond button it implies im giving level 3, until the spinner finishes.

![20210816-8G3lEjWq](https://user-images.githubusercontent.com/69529928/129576690-99d13e67-d217-4e91-9570-fb7c7032c487.gif)

**Comment by superzordon** [comment] 2021-08-16 14:09
Thanks for flagging. Going to reduce the size of the hoverable select box and add a delay to the pop-up. Here's what it will look like: 

https://user-images.githubusercontent.com/88362450/129577003-795e4698-b24a-41f4-928a-e6325145d24c.mov

**Comment by tijno** [comment] 2021-08-16 14:21
@superzordon 

1) can you show what happens when just clicking the diamond button without moving mouse?

2) can you try and show the behaviour paul and i demonstrated is resolved by slowing down the mouse movement? Diamond selector should not select any diamonds until mouse cursor is within the popup select box

**Comment by tijno** [comment] 2021-08-16 14:30
for info - https://github.com/bitclout/frontend/pull/395

**Comment by tijno** [comment] 2021-08-16 15:46
Looking good. Ill check now.

**Comment by tijno** [comment] 2021-08-16 15:54
@superzordon Safari on macOs still seems to have the issue

![20210816-ESq2cJAV](https://user-images.githubusercontent.com/69529928/129592327-3f2baa53-5faa-4716-9ff8-e72f01a0ebe4.gif)

Firefox on macOS looks fine - although animations are sluggish but thats probably firefox.

![20210816-1mNxNabP](https://user-images.githubusercontent.com/69529928/129592561-eda09e1b-1cd6-42d9-b2eb-065618730b12.gif)

**Comment by AdityaChaudhary0005** [comment] 2021-08-19 14:13
Another false trigger I noticed was in this post (https://bitclout.com/posts/1a70eb7cac28f70b1ed27c5988547f87a96f558fc4520859220ee01381668aaa?tab=posts)
Whenever you hover your mouse over the user tag (@creatorcapital), the diamond slider pops up.
I accidently diamonded this post while trying to click the user tag
![Screenshot from 2021-08-19 19-41-23](https://user-images.githubusercontent.com/55331140/130083775-f218c8b2-378f-4d7e-b58e-03425b5a7230.png)

**Comment by tijno** [comment] 2021-08-19 14:42
cant replicate it at that URL due to post stats - but scrolling down on the profile [here](https://bitclout.com/u/bigmountain) does show it - see gif below.

![20210819-07Oyif9i](https://user-images.githubusercontent.com/69529928/130089087-a29902b3-172f-4750-bdbb-0b880ba8fb9e.gif)

**Comment by superzordon** [comment] 2021-08-19 14:45
Thanks for flagging this. [This](https://github.com/bitclout/frontend/pull/406) should resolve.

**Comment by tijno** [comment] 2021-08-19 16:31
@superzordon perfect - fix just deployed works i think!
![20210819-nsyMMuL0](https://user-images.githubusercontent.com/69529928/130107270-296908ea-d9d7-4363-bab7-30b079790400.gif)

@iPaulPro this can probably be closed now?

**Comment by iPaulPro** [comment] 2021-08-19 16:35
> @iPaulPro this can probably be closed now? 

Yes, looks good!

**Closed** 2021-08-19 16:35 UTC
